FROM python:3.10
# Đặt thư mục làm việc
WORKDIR /project_dbt

# Cài đặt dbt và các adapter cần thiết
RUN pip install dbt-core dbt-trino dbt-oracle

# Sao chép toàn bộ mã nguồn dbt vào container
COPY . .


